# Site settings
title: KhoiVan|TechnicalArtist
description: My porfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://vanthekhoi.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Khoi Van
user_description: I'm a passionate Technical Artist lived in Ho Chi Minh City, Viet Nam. After graduated I joined Glass Egg Digital Media for 3 year as a quality-oriented Technical Artist. My main roles are develop new tools, create technical checklist for company project, improve tools performance, pipelines and workflow for productivity and efficiency.  
user_title: Technical Artist
email: vanthekhoi@gmail.com
# twitter_username: 
# github_username:  
# gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
